### ISSUE TITLE
Liberalcoins Shutdown

### ISSUE THREAD

**Issue by DiverterBTC** [cointastical/P2P-Trading-Exchanges#1]
![Screenshot_20200408-202214_Chrome](https://user-images.githubusercontent.com/56491191/78845531-cf884d00-79d6-11ea-8d24-d2d295e15d0a.jpg)
Liberalcoins has shut down, effective April 1, 2020 according to https://liberalcoins.com/.

**Comment by cointastical** [comment]
Removed, thank you for the information.
